// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW4BU5qAJN5Ih21uer1qYINUPLa5BpLac',
    appId: '1:994485523106:web:8499e204a1c1fda5953dfb',
    messagingSenderId: '994485523106',
    projectId: 'the-recipe-app-623b1',
    authDomain: 'the-recipe-app-623b1.firebaseapp.com',
    storageBucket: 'the-recipe-app-623b1.firebasestorage.app',
    measurementId: 'G-GG1W5EC3M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdKdELDc2KcsQmQ6Q_THz9B0vdP-rTpXw',
    appId: '1:994485523106:android:70c6b332a83d916f953dfb',
    messagingSenderId: '994485523106',
    projectId: 'the-recipe-app-623b1',
    storageBucket: 'the-recipe-app-623b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6QpwDe5WcICQ1HrO7KYREOXaeiQFufsE',
    appId: '1:994485523106:ios:d73aa09608d38f27953dfb',
    messagingSenderId: '994485523106',
    projectId: 'the-recipe-app-623b1',
    storageBucket: 'the-recipe-app-623b1.firebasestorage.app',
    iosBundleId: 'com.example.theRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6QpwDe5WcICQ1HrO7KYREOXaeiQFufsE',
    appId: '1:994485523106:ios:d73aa09608d38f27953dfb',
    messagingSenderId: '994485523106',
    projectId: 'the-recipe-app-623b1',
    storageBucket: 'the-recipe-app-623b1.firebasestorage.app',
    iosBundleId: 'com.example.theRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW4BU5qAJN5Ih21uer1qYINUPLa5BpLac',
    appId: '1:994485523106:web:92b627f7cd5b680a953dfb',
    messagingSenderId: '994485523106',
    projectId: 'the-recipe-app-623b1',
    authDomain: 'the-recipe-app-623b1.firebaseapp.com',
    storageBucket: 'the-recipe-app-623b1.firebasestorage.app',
    measurementId: 'G-55TPDTDKVG',
  );
}
